sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"

button:
  - platform: restart
    name: "${friendly_name} Restart"

  - platform: safe_mode
    name: "${friendly_name} Safe Mode"